[tool.black]
line-length = 100
target-version = ['py313']
skip-string-normalization = false
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.venv
  | __pycache__
  | env
  | build
  | dist
  | postgres_data
)/
'''

[tool.isort]
profile = "black"
force_sort_within_sections = true
known_first_party = ["app"]
line_length = 100
skip = [
  ".git",
  ".mypy_cache",
  ".venv",
  "__pycache__",
  "env",
  "build",
  "dist",
  "postgres_data"
]

[tool.pytest.ini_options]
pythonpath = "src"